{
    'description': 'Opened successfully',
    'changed_file': 378,
    'opened_successfully': True,
    'local_path': None,
    'client_version': '0.0.1',
    "transform_nodes": [],
    "shape_nodes": [],
    'scene_info': {
        'transforms': 4,
        'groups': 0,
        'empty_groups': 0,
        'meshes': 0,
        'verts': 0,
        'edges': 0,
        'faces': 0,
        'tris': 0,
        'uvs': 0,
        'ngons': 0,
        'materials': 2,
        'textures': 0,
        'cameras': 4,
        'joints': 0,
        'lights': 0,
        'blend_shapes': 0,
        'morph_targets': 0,
        'nurbs_curves': 1,
        'root_nodes': 1,
        'up_axis': '',
        'linear': '',
        'angular': '',
        'current_time': 1,
        'anim_start_time': 1,
        'anim_end_time': 1,
        'play_back_start_time': 1,
        'play_back_end_time': 1,
        'frame_rate': 1}
}
